### PR TITLE
Continue when not-yet-solvable

### PR DESCRIPTION
**Pull request by wolfv**
@beckermr this should fix the issues seen in the stackvana feedstock. 

conda-build relies on the solver to throw a non-resolvable error to continue trying the next output. It seems like a flaw in the meta.yaml design that it can't order the outputs before starting to solve (something that's fixed with the new recipe implementation in `boa`).

What we do in `boa`:

- we convert expressions such as `{{ pin_subpackage('stackvana-core-impl', exact=True) }}` to `stackvana-core-impl PIN_SUBPACKAGE exact=True,...`
- Since we've converted the function (without really evaluating it) we can still extract the desired package name (by applying `split(dep, 3)[0]` for example, same as for regular MatchSpecs).
- Since we can extract the name we can also just properly do a topological sort of all build outputs

### CODE REVIEW

**Comment by beckermr** [comment]
Huzzah!

**Comment by beckermr** [comment]
While this technically works, it will retry the full build 10 times. This will end up costing a lot of CI time for all of the outputs that do happen to build in the meantime. I am not sure what to do about this however.

**Comment by wolfv** [comment]
@beckermr I don't think that should be a big problem, it only tries the solve a couple of times without reloading repodata (and not the building).

I think the proper fix will be to switch to the new recipe format in the future :) Outputs are _much_ faster & improved that way (pre-ordering vs trying to solve).

**Comment by beckermr** [comment]
I am pretty sure conda-build has a way to avoid this. I expect that mamba is not hooked into that mechanism right now. There are two rounds of solver checks in conda build. It does a round before it builds and then again as it builds. Mamba is only failing on the second round and should be failing on the first round iiuic. I could be wrong though.

**Comment by wolfv** [comment]
I think I found a way to short-circuit this in conda-build ... the code is really hard to figure out :)

**Pull request merged**
