### PR TITLE
Use `update_index` from conda-index directly

### LINKED ISSUE #392: Conda-Build Dependency Compatibility Issue with API Changes in Version 24.1.0
After upgrading to conda-build version 24.1.0, we have encountered compatibility issues with certain APIs, specifically related to mambabuild. 

# Steps to Reproduce:

1. Upgrade conda-build to version 24.1.0.
2. Execute `conda mambabuild . --no-tests`
3. Observe 
```python
ImportError: cannot import name 'update_index' from 'conda_build.index' (/home/itay/.conda/envs/myvenv/lib/python3.10/site-packages/conda_build/index.py)
``` 

# Links to API Changes in `conda-build` 24.1.0:

[Release Notes](https://github.com/conda/conda-build/releases/tag/24.1.0)
[Specific PR](https://github.com/conda/conda-build/pull/5151)

# Additional Information:

# Workaround:

Downgrade conda-build to 3.28.4

# Related Issues:

# Environment Information:

**Operating System**: macOS Sonoma
**Conda Version**: 4.10.3
**Python Version**: 3.10.13

# Suggested solution:
Use `update_index` directly from `conda-index` at https://github.com/mamba-org/boa/blob/main/boa/cli/mambabuild.py#L16 

# Note: 

I not a contributor in this repo, that why I didn't create a PR. I guess that the version change created many more API breaks in this package, and this is just one indication. 
Feel free to contribute to this discussion, and let me know if there are any specific steps, code snippets, or logs that can help in resolving this issue. Thank you!

### PR DESCRIPTION
**Pull request by jaimergp**
Closes #392

### CODE REVIEW

**Comment by jaimergp** [comment]
CI errors are also present in `main`. The tests for `mambabuild` do pass :)

**Comment by wolfv** [comment]
Thanks! Argh, CI errors 👿

**Comment by mbargull** [comment]
Any chances for a quick `0.16.1` tag with this?

**Comment by mbargull** [comment]
There hasn't been a tag/release with this fix yet.
It would be good if someone could have a look at the additional compatibility changes proposed in gh-395 such that we could put out a new build that would work with recent `conda-build` versions.

**Pull request merged**
