### PR TITLE
For issue 313 use os.path.normpath not os.normpath when setting git_url.

### PR DESCRIPTION
**Pull request by ericvoltron**
This change came directly from the issue filed by Jon, who I work with.

### CODE REVIEW

**Comment by rigzba21** [comment]
This fix is for https://github.com/mamba-org/boa/issues/313.

**Comment by rigzba21** [comment]
Seeing this from the [failed linter](https://github.com/mamba-org/boa/actions/runs/3536371045/jobs/5935341207):
```bash
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: could not read Username for 'https://gitlab.com/': No such device or address
```
Looks like an issue with `pre-commit` trying to pull in `flake8` from a private gitlab repo?

**Comment by chrisburr** [comment]
> Looks like an issue with pre-commit trying to pull in flake8 from a private gitlab repo?

It's been moved to GitHub: https://github.com/PyCQA/flake8

**Comment by wolfv** [comment]
let me update the pre-commit config

**Comment by mariusvniekerk** [comment]
@wolfv can we get a release with this fix in pretty please?

**Pull request merged**
