### PR TITLE
add existence checks for grayskull, xtensor

### PR DESCRIPTION
**Pull request by madhur-tandon**

### CODE REVIEW

**Comment by wolfv** [comment]
this should fail on Windows :)

**Comment by wolfv** [comment]
Looks like the test is currently skipped on Windows: https://github.com/mamba-org/boa/blob/3fa68276980e2410d598860e37717d680c7d6cf9/tests/test_boa_build.py#L7-L9

Maybe we can un-skip it?

**Comment by madhur-tandon** [comment]
I think the tests here failed pre-maturely. It failed at `import grayskull` and thus, it didn't even reach `file existence` checks. Is there a problem with testing `noarch` packages on `windows` @wolfv?

**Comment by wolfv** [comment]
here is a traceback: https://github.com/mamba-org/boa/runs/4084017550?check_suite_focus=true#step:5:1175

**Pull request merged**
