### PR TITLE
Add build test

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by wolfv** [comment]
It's pulling a `mamba` from pip (which is not the `mamba` we need :)

**Comment by martinRenou** [comment]
Doing `mamba install mamba` fixes it on Ubuntu. Don't ask me.

**Comment by martinRenou** [comment]
Looks like the recipes I am testing are not building on OSX. Do you have an idea why?

```
checking whether the C compiler works... no
```

**Comment by martinRenou** [comment]
I'll try doing `mamba install compilers`

**Comment by wolfv** [comment]
How about skipping the C / C++ packages for now?
Just testing a simple Python / pip package build is fine with me.

**Comment by wolfv** [comment]
it can even be a fake package that just `touch $PREFIX/somefile` in the `build.sh`

**Comment by wolfv** [comment]
btw if you're interested in a micromamba based CI setup, here is a complete github actions for all three OS's: https://github.com/wolfv/multisheller/blob/main/.github/workflows/ci.yaml

**Comment by martinRenou** [comment]
Ok I'll look at it thks

**Pull request merged**
